### ISSUE TITLE
文档能不能详细点

### ISSUE THREAD

**Issue by ghost** [zodiacg/hexo-theme-rebiture#2]
1. 你的风格很好，我很喜欢，但是缺点也有。
2. 文档太不详细了，想修改的话不知道改哪里。
3. 标题栏太丑了，字体没有设置好。
4. 360 的 字体服务停掉了，所以主题的字体加载非常慢，建议换回 googleapis，现在 google 的字体服务已经好了。
5. 多说评论没有设置。

**Comment by zodiacg** [comment]
设计不是我设计的，完全是[kywk的hexo-theme-biture](https://github.com/kywk/hexo-theme-biture)，我仅仅是把他的ejs改写为swig，梳理了一下结构。所以涉及字体等风格上的问题抱歉我很难提供帮助。

由于我现在也不使用这个主题了，也没有时间和动力维护。如果你有进一步自定义的需求，可以fork做改动。hexo主题的结构以及swig都不难。
